# write exp_name every time when run code
exp_name: ???
seed: 0
batch_size: 1
eval_batch_size: 1
datasets:
- uf
- rd

wandb:
  enabled: true
  entity: null
  project: "alighnment"
minimum_log_interval_secs: 1.0

sample_during_eval: false
n_eval_model_samples: 1
local_run_dir: ${get_local_run_dir:${exp_name},${local_dirs}}
lr: 5e-6
gradient_accumulation_steps: 1
max_grad_norm: 1.0
max_length: 256
max_prompt_length: 128
n_epochs: 1
n_examples: 1500
n_eval_examples: 50
warmup_steps: 128
eval_every: 50

optimizer: AdamW
defaults:
- _self_
- model: facebook
- loss: dpo

local_dirs:
  - /scr-ssd
  - /scr
  - .cache
